---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wavefront-operator
  namespace: flux-system
spec:
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  serviceAccountName: kustomize-controller
  path: ./platform/staging/cluster01/observability-system
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
