apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability-system

resources:
  - sync.yaml
  - wavefront.yaml
  - https://github.com/wavefrontHQ/observability-for-kubernetes/releases/download/v2.9.0/wavefront-operator.yaml

# generators:
#   - wavefronttoken.yaml

patches:
  - patch: |
      - op: replace
        path: /spec/template/spec/image
        value: projects.registry.vmware.com/tanzu_observability/kubernetes-operator:2.9.0
    target:
      kind: Deployment
      name: wavefront-controller-manager
