apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability-system

resources:
  - https://github.com/wavefrontHQ/observability-for-kubernetes/releases/download/v2.9.0/wavefront-operator.yaml

patches:
  - patch: |
      - op: replace
        path: /spec/template/spec/image
        value: projects.registry.vmware.com/tanzu_observability/kubernetes-operator:2.9.0
    target:
      kind: Deployment
      name: wavefront-controller-manager

patchesStrategicMerge:
- |-
  apiVersion: wavefront.com/v1alpha1
  kind: Wavefront
  metadata:
    name: wavefront
    namespace: observability-system
  spec:
    clusterName: dev
    wavefrontUrl: vmware.wavefront.com
    dataCollection:
      metrics:
        enable: true
      logging:
        enable: true
    dataExport:
      wavefrontProxy:
        enable: true