apiVersion: wavefront.com/v1alpha1
kind: Wavefront
metadata:
  name: wavefront
  namespace: observability-system
spec:
  clusterName: dev
  wavefrontUrl: https://vmware.wavefront.com/api
  dataCollection:
    metrics:
      enable: true
    logging:
      enable: false
  dataExport:
    wavefrontProxy:
      enable: true