apiVersion: wavefront.com/v1alpha1
kind: Wavefront
metadata:
  name: wavefront
  namespace: observability-system
spec:
  clusterName: dev
  wavefrontUrl: vmware.wavefront.com
  dataCollection:
    metrics:
      enable: true
    logging:
      enable: true
  dataExport:
    wavefrontProxy:
      enable: true